### ISSUE TITLE
Helper to resolve all links and serialize all Structured Text fields in a document

### ISSUE THREAD

**Issue by angeloashmore** [prismicio/prismic-helpers#16]
A function to traverse a document's fields and convert all Rich Text and Title fields to HTML and text could help users simplify their code.

If they are using `asHTML` or `asText` throughout their project, this would allow one call to replace all of them.

This function could be called `resolveAndSerializeDocument` as it resolves links and serializes Structured Text.

```javascript
import * as assert from 'assert'
import * as prismic from '@prismicio/client'
import * as prismicH from '@prismicio/helpers'

import { linkResolver, htmlSerializer } from '../utils'

const endpoint = prismic.getEndpoint('qwerty')
const client = prismic.createClient(endpoint)

const document = client.getByUID('blog_post', 'my-post')
const convertedDocument = prismicH.resolveAndSerializeDocument(document, linkResolver, htmlSerializer)

assert.deepEqual(
  convertedDocument.data.title,
  {
    text: 'My Title',          // Serialized via prismicH.asText
    html: '<h1>My Title</h1>', // Serialized via prismicH.asHTML
    data: document.data.title  // The original Rich Text object
  }
)

assert.deepEqual(
  convertedDocument.data.link,
  {
    ...document.data.link
    url: '/resolve-link', // Resolved via prismicH.asLink
  }
)
```

Detection of Structured Text fields is somewhat unreliable, but not impossible. Every element in the field should contain a `type` field.

(Credit to @asyarb for the idea)

**Comment by lihbr** [comment]
Hey, while I, to some extent, like the idea, I'd like to understand a bit more the use case/need for such a function.

Basically it feels really high level for me. I haven't seen this pattern before this issue and I feel like most higher-level frameworks libraries we (will) develop already take care of doing that heavy lifting under the hood, while allowing developers to write self-explanatory (verbose?) code (examples in Vue):

```html
<prismic-rich-text :field="doc.richtext" />

<prismic-link :field="doc.link">My link</prismic-link>
```

**Comment by angeloashmore** [comment]
The function serves as a way to universalize the document's data early on. Rather than convert Rich Text at each area that will require its HTML or text representation, it can be done once immediately after document fetching.

"Universalize" in this case means to effectively opt-out of Prismic's proprietary format and fall back to more standard formats, like HTML and text. The content can then be used in the same way as other data in an app, such as an API response from Shopify that returns HTML and text strings.

If the Rich Text format is still needed, such as to serialize into React or Vue components, its raw data is still available at the `.data` field (or maybe this should be named `.richText` to be clearer; see https://github.com/angeloashmore/gatsby-source-prismic/issues/395).

Doing this has a few benefits:

1. Consuming renderers (e.g. React/Vue components) work with more basic content: HTML and text strings.
2. `@prismicio/helpers` and `@prismicio/richtext` does not need to be sent to the client.
3. If used in an SSR context, parsing is no longer required in the browser which could lead to better performance.

## A concrete example of its benefits

Take the following component as an example (sorry, it's in React because I don't know Vue 😁).

```tsx
import * as prismicT from '@prismicio/types'
import { RichText } from 'prismic-reactjs'

type MyComponentProps = {
  title: prismicT.RichTextField
}

const MyComponent = ({ title }: MyComponentProps) => {
  return (
    <div>
      <RichText render={title} />
    </div>
  )
}
```

To use the component, a user must provide a Rich Text field's content to render the title. If a user wanted to use this component in a non-Prismic context, the `title` prop would need to be created as Rich Text by hand.

```tsx
<MyComponent title={document.data.title} />
<MyComponent
  title={[
    type: 'heading1',
    text: 'My Title',
    spans: []
  ]}
/>
```

Compare that component to this (note that there are no imports):

```tsx
type MyComponentProps = {
  title: string
}

const MyComponent = ({ title }: MyComponentProps) => {
  return (
    <div>
      <h1>{title}</h1>
    </div>
  )
}
```

The component now accepts the `title` prop as a string. It can be used with Prismic content by calling `RichText.asText` beforehand. It can also be used without Prismic content by passing a string directly.

The call to `asText` can happen anywhere outside the component, whether in a server-specific call or directly when passing it to the prop.

```typescript
<MyComponent title={RichText.asText(document.data.title)} />
<MyComponent title="My Title" />
```

This component can now accept content from anywhere, including, for example, data from the Shopify API.

If the document is called with `resolveAndSerializeDocument` early in the lifecycle, the example looks like this:

```tsx
<MyComponent title={document.data.title.text} />
<MyComponent title="My Title" />
```

## Using `asHTML` and `asText` (via `@prismicio/helpers` or UI library components)

<img src="https://user-images.githubusercontent.com/8601064/122271497-2d39e400-ce7b-11eb-8706-87b0d2c6de67.png" width="400" />

## Using `resolveAndSerializeDocument `

<img src="https://user-images.githubusercontent.com/8601064/122271552-3a56d300-ce7b-11eb-8a99-0a5441537228.png" width="400" />

**Comment by asyarb** [comment]
Hey! Thanks for putting this together. Just wanted to chime in here with another practical benefit of such a helper:

**Defer `RichText` evaluation entirely to build-time**

With the current usage of `RichText`, there isn't an (easy) way to defer runtime evaluation of Prismic rich text fields to just build-time. Most static site generators (e.g. NextJS) will re-run any calls to `RichText.asText` or `RichText.asHTML` during hydration / lazy hydration. 

A helper like `resolveAndSerializeDocument` allows developers to exclusively parse Prismic rich text in functions like `getStaticProps` to ensure we're only doing this work at build/SSR time, and not on the client.

```jsx
import * as prismic from '@prismicio/client'
import * as prismicH from '@prismicio/helpers'

export default function Page({ content }) { 
  return <div dangerouslySetInnerHTML={{ __html: content }} /> 
}

export function getStaticProps() {
  const doc = client.getByUID('page', 'home-page')
  const convertedDoc = prismicH.resolveAndSerializeDocument(doc)

  return { props: { content: convertedDoc.data.content.html } }
}
```

**Comment by lihbr** [comment]
Hey there!

I'm sorry for the lack of progress here. We had a discussion about this topic some time ago and didn't make any progress on it.

My position on it is now the following: I get the benefit but would prefer advanced users to keep rolling their own implementations. To take full advantage of that pattern and shave a few KB from the final bundle there are some quite low-level optimizations to be performed, as-in, proper code splitting isn't so trivial to achieve depending on the context. Because of that, I'm afraid most users won't benefit from it and that it will just create confusion around it (and I'd prefer users to optimize their 15 KB favicon before worrying about splitting 3 KB of JS). I still acknowledge the benefit of being able to build agnostic components though.

In any case, I'm not vetoing anything, nor do I consider having that power, so we can keep discussing it if you feel like it.

cc @angeloashmore

**Comment by lihbr** [comment]
So far we've decided to not move on with such a feature, therefore, we'll close this issue for now. May it be reopened if further consideration is desired.

For reference, here's a snippet achieving the desired result (serializing rich texts and resolving links, _untested_), with some edge cases not handled (cf. comments):

```javascript
import * as prismicH from "@prismicio/helpers";

const allNodeTypes = Object.values(prismicH.Element);

const resolveAndSerializeObject = (obj, linkResolver, htmlSerializer) => {
	Object.keys(obj).map((key) => {
		if (typeof obj[key] === "object") {
		// Not a primitive

			if ("link_type" in obj[key]) {
			// Link case

				obj[key].url = prismicH.asLink(obj[key], linkResolver);
			} else if (Array.isArray(obj[key])) {
			// Title, Rich Text, Group, and SliceZone case

				if (!obj[key].length) {
				// An empty Title or Rich Text field cannot be differenciated from a Group or SliceZone,
				// assuming Title/Rich Text here but might lead to some issues

					obj[key] = {
						html: "",
						text: "",
						data: obj[key],
					};
				} else if (
					"type" in obj[key][0] && allNodeTypes.includes(obj[key][0].type)
				) {
				// A filled Title or Rich Text field
					obj[key] = {
						html: prismicH.asHTML(obj[key], linkResolver, htmlSerializer),
						text: prismicH.asText(obj[key]),
						data: obj[key],
					};
				}
			}
		}
	});

	return obj;
};

export const resolveAndSerializeDocument = (doc, linkResolver, htmlSerializer) => {
	// Resolve and serialize document main fields
	doc.data = resolveAndSerializeObject(doc.data, linkResolver, htmlSerializer);

	// Resolve and serialize Group and SliceZone
	Object.keys(doc.data).map((key) => {
		if (Array.isArray(doc.data[key])) {
		// If Group or SliceZone, Title and Rich Text were already serialized

			if (
				doc.data[key].every((slice) =>
					"slice_type" in slice &&
					"primary" in slice &&
					"items" in slice
				)
			) {
			// SliceZone case

				doc.data[key] = doc.data[key].map((slice) => {
					return {
						...slice,
						primary: resolveAndSerializeObject(slice.primary, linkResolver, htmlSerializer),
						items: slice.items.map((item) => {
							return resolveAndSerializeObject(item, linkResolver, htmlSerializer);
						}),
					}
				});
			} else {
			// Group case

				doc.data[key] = doc.data[key].map((item) =>
					resolveAndSerializeObject(item, linkResolver, htmlSerializer)
				);
			}
		}
	});

	return doc;
};
```

**Comment by asyarb** [comment]
Hey @lihbr!

Thank you for the snippet and suggestion forward for a path like this! With the latest changes to Prismic's libraries (faster and lighter rich-text serialization + component-centric APIs) I do agree that functionality like this shouldn't be necessary for most projects.

Just wanted to say thanks for your folks continuous work on improving the Prismic DX!
