### ISSUE TITLE
`isFilled` helper

### ISSUE THREAD

**Issue by angeloashmore** [prismicio/prismic-helpers#33]
A helper that determines if a field is filled or not could be helpful.

For example, the following code is needed to check if a Rich Text field is empty (note that a Rich Text field can be stuck with `<p></p>` even when emptied):

```tsx
{prismicH.asText(title) && (
        <h3 className="plan__title">
                <PrismicText field={title} />
        </h3>
)}
```

It doesn't convey intent as well as this:

```tsx
{prismicH.isFilled(title) && (
        <h3 className="plan__title">
                <PrismicText field={title} />
        </h3>
)}
```

Link fields are currently difficult to determine if they are filled or not. It is not something that can be inlined with other code (at least I don't think so). Thus, abstracting it to a helper could be useful.

Detecting field types to determine which kind of check to make may be fragile, but it could be possible.

I don't have a proposal on its implementation, but any thoughts on its usefulness?

**Comment by lihbr** [comment]
That would be a nice, almost expected addition to helpers.

I think it's definitely doable, our types are starting to be robust and there should be an easy way to detect each type (rich texts are arrays, most simple field defaults to `null`, only links can be a bit funny~

We can mark such helper as experimental also if we want to keep the freedom of breaking changes for those within the field testing timeframe :)

**Comment by angeloashmore** [comment]
Added in #34
