### ISSUE TITLE
`prismicH.asImageSrc` using `width` instead of `w` doesn't do anything

### ISSUE THREAD

**Issue by Odas0R** [prismicio/prismic-helpers#63]
### Versions

- @prismicio/helpers: ^2.3.9
- node: v16.17.1

### Steps to reproduce

```ts
  const imgSrc = prismicH.asImageSrc(images[0]?.image, {
    width: 250, // does not work
    height: 250, // does not work
    q: 75,
    fm: "webp",
    fit: "crop",
  });

  const imgSrc = prismicH.asImageSrc(images[0]?.image, {
    w: 250, // works
    h: 250, // works
    q: 75,
    fm: "webp",
    fit: "crop",
  });
```

### What is expected?

Using the param `width` and `height` optimize the image

### What is actually happening?

The param `width` and `height` have no effect

**Comment by lihbr** [comment]
Hey there, thank you so much for contributing. I'm sorry we failed to get back to you in a timely manner.

I tried reproducing without success, those tests pass as expected (committed version: https://github.com/prismicio/prismic-helpers/commit/5ee387a4abbefdb50970cc80585795af11fdd752 /CI results: https://github.com/prismicio/prismic-helpers/actions/runs/5465804619/jobs/9949788226):
```typescript
expect(
	asImageSrc(field, {
		w: 250,
		h: 250,
		q: 75,
		fm: "webp",
		fit: "crop",
	}),
).toBe(`${field.url}&w=250&h=250&q=75&fm=webp&fit=crop`);
expect(
	asImageSrc(field, {
		width: 250,
		height: 250,
		q: 75,
		fm: "webp",
		fit: "crop",
	}),
).toBe(`${field.url}&width=250&height=250&q=75&fm=webp&fit=crop`);
```

Equivalent images appear to be rendered as expected:
- `width`/`height`: https://images.prismic.io/prismicio-docs-v3/72606106-11e9-4da2-8dd1-14f779eda024_Sign-up+form+slice.png?auto=compress%2Cformat&rect=0%2C0%2C1246%2C707&width=250&height=250&q=75&fm=webp&fit=crop
- `w`/`h`: https://images.prismic.io/prismicio-docs-v3/72606106-11e9-4da2-8dd1-14f779eda024_Sign-up+form+slice.png?auto=compress%2Cformat&rect=0%2C0%2C1246%2C707&w=250&h=250&q=75&fm=webp&fit=crop

I'm confused if I got your issue correctly, maybe this was a regression back then on Imgix's end? Well let me know, I'm closing it for now but happy to reopen~
