### ISSUE TITLE
Nuxtjs 2 using `prismicH.Element` return error `need an appropriate loader`

### ISSUE THREAD

**Issue by KoMiToRaY** [prismicio/prismic-helpers#66]
### Versions

this is my package.json

```json
{
  "name": "simple-nuxt",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "prisma generate && npm run generate",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint:eslint": "eslint --ext \".js,.vue\" --ignore-path .gitignore .",
    "eslint": "npm run lint:eslint",
    "audit": "npm audit",
    "lint:stylelint": "stylelint \"**/*.{vue,css}\""
  },
  "dependencies": {
    "@nuxtjs/dotenv": "^1.4.1",
    "@prisma/client": "4.15.0",
    "@prismicio/helpers": "^2.3.9",
    "core-js": "^3.19.3",
    "crypto-js": "^4.1.1",
    "express": "^4.18.2",
    "nuxt": "^2.17.0",
    "vue": "^2.6.14",
    "vue-server-renderer": "^2.6.14",
    "vue-template-compiler": "^2.6.14",
    "webpack": "^4.46.0"
  },
  "devDependencies": {
    "@nuxt/image": "^0.7.1",
    "@nuxtjs/prismic": "^1.4.2",
    "@nuxtjs/tailwindcss": "^6.7.0",
    "postcss": "^8.4.24",
    "prisma": "^4.15.0",
    "vee-validate": "^3.3.0"
  }
}
```

### Steps to reproduce
Using nuxtjs 2 and create a lib folder with a js file :

```js
import * as prismicH from '@prismicio/helpers'
const Elements = prismicH.Element

console.log(Elements)
```
the error appears with this line of code `import * as prismicH from '@prismicio/helpers'`

### What is actually happening?
![image](https://github.com/prismicio/prismic-helpers/assets/10220997/3afb9426-bf64-4782-850c-4b1eaa24f18e)

**Comment by KoMiToRaY** [comment]
bug fixed with this version `"@prismicio/helpers": "^2.1.0",`

**Comment by lihbr** [comment]
Hey there, thanks for contributing!

Interesting, for modern version you might need to declare `@prismicio/helpers` as part of the `build.transpile` array in your Nuxt config 🤔

**Comment by lihbr** [comment]
Hey there, I'll assume declaring `@prismicio/helpers` in your config `build.transpile` array did the trick. I'm closing this ticket, but happy to reopen it if needed~

Thanks for contributing!
